namespace Contpaqi.SistemasComerciales.Sdk.Extras.Modelos
{
    public class ClienteProveedorComercial
    {
        // Propiedades tCteProv
        public string CodigoCliente;
        public string RazonSocial;
        public string FechaAlta;
        public string RFC;
        public string CURP;
        public string DenominacionComercial;
        public string RepresentanteLegal;
        public string NombreMoneda;
        public int ListaPreciosCliente;
        public double DescuentoMovimiento;
        public int BanderaVentaCredito;
        public string CodigoValorClasificacionCliente1;
        public string CodigoValorClasificacionCliente2;
        public string CodigoValorClasificacionCliente3;
        public string CodigoValorClasificacionCliente4;
        public string CodigoValorClasificacionCliente5;
        public string CodigoValorClasificacionCliente6;
        public int TipoCliente;
        public int Estatus;
        public string FechaBaja;
        public string FechaUltimaRevision;
        public double LimiteCreditoCliente;
        public int DiasCreditoCliente;
        public int BanderaExcederCredito;
        public double DescuentoProntoPago;
        public int DiasProntoPago;
        public double InteresMoratorio;
        public int DiaPago;
        public int DiasRevision;
        public string Mensajeria;
        public string CuentaMensajeria;
        public int DiasEmbarqueCliente;
        public string CodigoAlmacen;
        public string CodigoAgenteVenta;
        public string CodigoAgenteCobro;
        public int RestriccionAgente;
        public double Impuesto1;
        public double Impuesto2;
        public double Impuesto3;
        public double RetencionCliente1;
        public double RetencionCliente2;
        public string CodigoValorClasificacionProveedor1;
        public string CodigoValorClasificacionProveedor2;
        public string CodigoValorClasificacionProveedor3;
        public string CodigoValorClasificacionProveedor4;
        public string CodigoValorClasificacionProveedor5;
        public string CodigoValorClasificacionProveedor6;
        public double LimiteCreditoProveedor;
        public int DiasCreditoProveedor;
        public int TiempoEntrega;
        public int DiasEmbarqueProveedor;
        public double ImpuestoProveedor1;
        public double ImpuestoProveedor2;
        public double ImpuestoProveedor3;
        public double RetencionProveedor1;
        public double RetencionProveedor2;
        public int BanderaInteresMoratorio;
        public string TextoExtra1;
        public string TextoExtra2;
        public string TextoExtra3;
        public double ImporteExtra1;
        public double ImporteExtra2;
        public double ImporteExtra3;
        public double ImporteExtra4;
        // Propiedades Extras
        public int IdCliente { get; set; }
    }
}
